### ISSUE TITLE
from pyogg import OpusDecoder error

### ISSUE THREAD

**Issue by cklam12345** [Zuzu-Typ/PyOgg#112]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "PyOgg-master/pyogg/__init__.py", line 6, in <module>
    from .opus import PYOGG_OPUS_AVAIL, PYOGG_OPUS_FILE_AVAIL, PYOGG_OPUS_ENC_AVAIL
  File "PyOgg-master/pyogg/opus.py", line 437, in <module>
    libopus.opus_encoder_create.argtypes = [opus_int32, c_int, c_int, c_int_p]
                                                                      ^^^^^^^
NameError: name 'c_int_p' is not defined. Did you mean: 'c_int'?

**Comment by kalradivyanshu** [comment]
@cklam12345 `c_int_p` is defined in libopus, you need to install all the dependencies:

```bash
sudo apt install libogg-dev libopusenc-dev libflac-dev libopusfile-dev libopus-dev libvorbis-dev
```

See: https://pyogg.readthedocs.io/en/latest/installation.html#linux

**Comment by ozanyurt** [comment]
I am using mac os x m1 and this works for me https://github.com/TeamPyOgg/PyOgg/issues/113#issuecomment-2585724522
